name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build and test Android project
      run: |
        ./gradlew build assembleDebug
      env:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
