name: Android CI

on:
  push:
    branches: [ main ]

env:
  ANDROID_HOME: /usr/local/android-sdk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Android SDK components
      run: |
        echo 'y' | sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
      env:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
      if: ${{ !startswith(github.ref, 'refs/tags/') }}

    - name: Build and test Android project
      run: |
        ./gradlew build connectedCheck
      env:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
