name: Android CI

on:
  push:
    branches: [ "main","develop","feature" ]
  pull_request:
    branches: [ "main","develop","feature" ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Access ITENEUM_KEY
      env:
        ITENEUM_KEY: ${{ secrets.APOD_API_KEY }}      
      run: echo ITENEUM_KEY=${{ APOD_API_KEY }} > ./secure.properties
      
    - name: Check secure.properties
      run: cat ./secure.properties

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11


    - name: Build and test Android project (Temporal)
      run: |
          ./gradlew build -x test
      env:
        ANDROID_SDK_ROOT: /usr/local/android-sdk
