name: Deploy-Android-TEST

on:
  push:
    branches: [ "main","feature" ]
  pull_request:
    branches: [ "main","feature" ]

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_KK }}
  APP_NAME: ${{ 'MyApp-Android/ENV_TEST'  }}  
  TESTING_GROUP: ${{  'ENV_TEST'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}  
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build android
      run:  |
        ./gradlew assembleRelease -x test
