name: Deploy-Android-TEST

on:
  push:
    branches: [ "main","feature" ]
  pull_request:
    branches: [ "main","feature" ]

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_KK }}
  APP_NAME: ${{ 'MyApp-Android/ENV_TEST'  }}  
  TESTING_GROUP: ${{  'ENV_TEST'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-release.apk'  }}  
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Install dependencies
        run: npm install
      - name: Build android
        run: npm run cd android && ./gradlew build -x test
        
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
